#!/usr/bin/env python2.7

#system
import optparse
import ConfigParser
import sys

#local
sys.path.append("../aeries-api")
import Main

CONFIG_FILE =       'aeriesrc' #'~/.aeriesrc'
USER_SECTION =      'User'
EMAIL_OPTION =      'email'
PASSWORD_OPTION =   'password'
         
def main():
    p = optparse.OptionParser()
    p.add_option('--email', '-e',
                 action='store', dest='email',
                 default=None)
    p.add_option('--password', '-p',
                 action='store', dest='password',
                 default=None)
    p.add_option('--grades', '-g',
                 action='store_true', dest='grades',
                 default=False)
    p.add_option('--assignments', '-a',
                 action='store_true', dest='assignments',
                 default=False)
    p.add_option('--gradebook', '-b',
                 action='store', dest='gradebook',
                 default=None)
    p.add_option('--set', '-s',
                 action='store_true', dest='set',
                 default=False)
    (options, arguments) = p.parse_args()


    config = ConfigParser.RawConfigParser()
    config.read(CONFIG_FILE)

    if options.email != None:
        if options.set:
            config.set(USER_SECTION, EMAIL_OPTION, options.email)
        email = options.email
    else:
        email = config.get(USER_SECTION, EMAIL_OPTION)
    if options.password != None:
        if options.set:
            config.set(USER_SECTION, PASSWORD_OPTION, options.password)
        password = options.password
    else:
        password = config.get(USER_SECTION, PASSWORD_OPTION)

    if options.grades:
        print Main.get('grades', email, password)
    elif options.assignments:
        print Main.get('assignments', email, password)
    elif options.gradebook != None:
        print Main.get('gradebook', email, password, gradebook=options.gradebook)

    # write changes to the config file (if changed with the -s option)
    f = open(CONFIG_FILE, 'w')
    config.write(f)

if __name__ == '__main__':
    main()
